<?php
/**
 * @var $block \Opengento\DevPluginList\Block\Adminhtml\Index
 */
try {
    $pluginList = $block->getPluginList();
    echo '<div><h1>There is '.$pluginList['count']['total']. ' total plugins</h1></div>';
    echo '<div><h1>There is '.$pluginList['count']['enable']. ' plugins enable</h1></div>';
    echo '<div><h1>There is '.$pluginList['count']['total']-$pluginList['count']['enable']. ' plugins disable</h1></div>';
   // echo $block->extracted($pluginList['plugins']);

    echo $block->displayPluginList($pluginList['plugins']);
} catch (\Magento\Framework\Exception\FileSystemException|ReflectionException $e) {
    echo '<div><h1>'.$e->getCode().'</h1></div>';
    echo '<div><h1>'.$e->getMessage().'</h1></div>';
}



